In [1]:
#importamos librerías necesarias y generamos dataframe a partir de los datos
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import os
import requests
import json
import plotly.express as px
from plotly.subplots import make_subplots

In [2]:
#generamos dataframe
gun_violence = pd.read_csv('C:\coderhouse\coderhouse\proyecto_final\gun_violence_full.csv')

In [3]:
#agregamos una columna con el número 1 en todos los registros
gun_violence['incident_amount'] = 1
gun_violence.head()

,incident_id,date,state,city_or_county,n_killed,n_injured,latitude,longitude,n_guns_involved,tavg,...,participant_suspect_male,participant_suspect_female,participant_suspect_child,participant_suspect_teen,participant_suspect_adult,participant_suspect_injured,participant_suspect_injured_arrested,participant_suspect_unharmed,participant_suspect_unharmed_arrested,participant_suspect_killed
0,92114,2014-01-01,Kentucky,Lexington,0,1,38.0507,-84.4829,NaN,2.0,...,0,0,0,0,0,0,0,0,0,0
1,92117,2014-01-01,Kentucky,Cynthiana,0,1,38.4333,-84.3542,1.0,NaN,...,1,0,0,0,1,0,0,0,1,0
2,92119,2014-01-01,Kentucky,Louisville,0,1,38.2501,-85.8150,NaN,2.9,...,0,0,0,0,0,0,0,0,0,0
3,92125,2014-01-01,Oklahoma,Lawton,0,0,34.6347,-98.4222,NaN,3.6,...,1,0,0,0,0,0,0,1,0,0
4,92131,2014-01-01,New York,Bronx,0,1,40.8179,-73.8628,NaN,-1.4,...,0,0,0,0,0,0,0,0,0,0

In [4]:
#sumando los incidentes por estado
gunstate = gun_violence.groupby(['state']).sum()
gunstate.sort_values(by=['state'])

,incident_id,n_killed,n_injured,latitude,longitude,n_guns_involved,tavg,tmin,tmax,prcp,...,participant_suspect_male,participant_suspect_female,participant_suspect_child,participant_suspect_teen,participant_suspect_adult,participant_suspect_injured,participant_suspect_injured_arrested,participant_suspect_unharmed,participant_suspect_unharmed_arrested,participant_suspect_killed
state,,,,,,,,,,,,,,,,,,,,,
Alabama,2332440033,1668,2580,145994.4597,-3.843650e+05,2412.0,72782.7,51252.1,96735.8,11850.7,...,3081,265,14,221,3122,149,42,1281,1628,226
Alaska,523432626,234,267,57683.9245,-1.391911e+05,750.0,2657.0,-1017.6,6247.9,1049.1,...,822,78,5,50,862,13,15,194,660,37
Arizona,898371628,940,847,56260.2871,-1.888798e+05,1165.0,35957.1,25870.8,45988.1,647.4,...,1185,100,9,60,1220,64,40,476,409,233
Arkansas,1193597550,675,1181,75770.9213,-1.996282e+05,1365.0,30252.2,23478.8,43555.3,3950.0,...,1727,139,8,126,1715,62,16,737,926,92
California,6728201648,4872,6109,442100.0697,-1.469601e+06,8835.0,206710.7,143083.8,282431.0,7235.6,...,8858,535,16,595,8732,300,188,3478,4634,772
Colorado,1018447517,627,681,68879.8245,-1.846890e+05,1404.0,18176.3,5734.5,31189.0,1368.9,...,1496,152,5,144,1531,35,51,496,965,169
Connecticut,1210127550,305,1047,95393.8635,-1.678371e+05,1690.0,29920.2,19104.8,40818.2,4806.3,...,2064,99,1,121,2046,31,27,737,1351,39
Delaware,654612041,196,776,53963.0954,-1.031497e+05,827.0,15507.5,9448.2,21619.4,3503.0,...,935,52,1,96,892,13,5,499,343,18
District of Columbia,737003116,390,1004,65179.6390,-1.290313e+05,595.0,28890.2,21204.9,37219.3,4591.6,...,1158,19,2,49,1198,15,12,896,182,21
Florida,5267316136,3297,5532,287347.5810,-8.343812e+05,6540.0,219323.1,178402.1,267930.1,24194.4,...,8271,595,32,882,7889,266,164,3554,4609,525
Georgia,3236740773,2153,3360,216043.9407,-5.470167e+05,3763.0,117996.5,84936.2,156334.6,12619.4,...,5651,458,33,503,5076,184,108,2707,2719,303
Hawaii,113950217,56,73,4398.4525,-3.351983e+04,161.0,4851.0,4142.7,5639.6,706.7,...,204,28,0,6,228,5,5,55,148,17
Idaho,276297088,141,123,21935.5570,-5.693614e+04,544.0,4627.7,1825.2,7481.7,227.8,...,452,61,6,33,486,14,14,87,346,48
Illinois,7783289980,2909,12031,584661.5928,-1.238671e+06,9553.0,190778.9,124342.7,257580.3,39286.9,...,7370,214,11,440,4706,124,47,5024,2516,143
Indiana,2262371134,1346,2275,171680.8554,-3.672795e+05,3481.0,48914.1,28580.4,69334.9,8881.2,...,3081,201,15,276,2878,81,35,1375,1737,127
Iowa,810864068,232,619,63481.7912,-1.403982e+05,1145.0,15531.8,7553.4,23531.5,2263.8,...,1366,97,3,173,1244,27,25,433,941,43
Kansas,761895390,446,683,52026.1046,-1.307888e+05,835.0,16381.0,10269.1,22761.2,2581.6,...,1098,82,5,98,995,31,28,509,634,70
Kentucky,1559993039,935,1456,114985.9096,-2.595567e+05,1990.0,39857.4,26395.4,55119.7,7028.0,...,2600,283,18,231,2667,82,46,1063,1368,176
Louisiana,3281771434,1854,3569,194343.3731,-5.799819e+05,3683.0,107281.3,85498.8,132091.2,15955.4,...,5045,313,26,482,4851,163,78,2686,2138,191
Maine,326135053,102,127,26630.4312,-4.193858e+04,603.0,3471.5,990.0,6063.2,760.0,...,628,80,0,21,691,7,17,172,473,35
Maryland,2612092129,1509,2811,187790.0245,-3.668978e+05,2877.0,72791.7,53600.5,93021.9,11140.4,...,2348,110,6,161,2364,64,28,824,1101,110
Massachusetts,2154821815,414,1345,167050.4005,-2.827930e+05,3439.0,44675.5,24620.4,64581.2,9107.7,...,4215,283,1,305,4195,19,33,1205,3225,50
Michigan,2158826213,1319,2331,180705.0166,-3.553994e+05,3143.0,44727.4,25152.4,64370.1,5881.5,...,3344,258,19,323,3220,96,55,1776,1475,154
Minnesota,744179007,387,624,59170.9593,-1.223012e+05,1059.0,11607.1,5332.6,17752.8,2466.6,...,1161,93,6,110,1136,26,15,422,733,91
Mississippi,1502995457,1015,1584,89330.3064,-2.472253e+05,1482.0,37857.5,26417.7,51092.6,5823.1,...,2060,174,13,147,2122,88,14,888,1131,114
Missouri,2499970097,1828,2458,170604.1182,-4.057913e+05,3243.0,62277.0,40786.0,84616.2,9914.1,...,3194,220,21,271,2874,97,92,1391,1817,217
Montana,243146470,136,103,19050.8334,-4.561748e+04,380.0,2732.0,697.6,4720.9,339.4,...,349,30,0,15,358,5,10,79,239,39
Nebraska,581040840,197,574,44581.2557,-1.045183e+05,751.0,13781.4,7522.0,20087.8,2414.4,...,938,67,4,105,789,9,12,414,560,46
Nevada,726410144,672,704,51449.8239,-1.619699e+05,728.0,27284.7,18729.7,35513.4,383.1,...,1092,93,1,58,1128,53,28,520,365,131
New Hampshire,349161954,80,118,28624.3803,-4.741493e+04,637.0,6313.6,2704.3,10010.3,895.4,...,663,65,1,29,696,1,5,215,473,26
New Jersey,2169970316,1023,2216,175459.6258,-3.236917e+05,2688.0,57458.5,37390.2,77803.0,7536.3,...,3402,184,6,253,3413,60,35,1436,1389,85
New Mexico,555949192,385,339,33777.3720,-1.036049e+05,713.0,14299.7,7658.5,21120.9,358.2,...,894,85,5,55,883,31,33,248,493,113
New York,4056411165,1556,4523,338920.1215,-6.101530e+05,5612.0,88788.5,54260.9,123287.6,16446.6,...,6958,498,9,538,6594,73,76,2614,4057,147
North Carolina,3110801403,1952,3643,223633.0630,-5.004951e+05,3274.0,91732.8,64708.0,130338.9,11022.2,...,5198,369,17,463,4988,153,60,2465,2560,233
North Dakota,197431366,53,96,17025.3213,-3.602850e+04,292.0,2437.2,352.0,4509.7,223.0,...,339,32,2,12,353,9,9,78,260,15
Ohio,3962399877,2152,4496,306902.7411,-6.274958e+05,5757.0,90738.2,55021.8,127326.0,15287.8,...,5666,317,24,446,5156,123,71,2918,2360,233
Oklahoma,1140192634,775,885,69939.1596,-1.893264e+05,1501.0,32566.2,21925.5,43793.1,3321.3,...,1851,195,6,183,1761,70,52,704,1090,166
Oregon,846525534,377,593,71955.7872,-1.974206e+05,1525.0,19261.8,11550.1,27893.4,2877.1,...,1573,145,5,94,1631,36,39,381,1097,100
Pennsylvania,3631651617,2059,4264,281007.5731,-5.352824e+05,4604.0,86142.6,54238.6,118627.6,14615.5,...,4868,284,16,338,4745,148,78,2266,1646,236
Rhode Island,330491148,50,298,27341.5124,-4.671859e+04,513.0,8777.8,5492.2,12160.7,1757.4,...,678,37,0,27,653,8,7,280,403,8
South Carolina,2512462003,1403,2487,169865.1444,-4.052998e+05,2800.0,90070.1,65322.1,117736.2,9242.3,...,4373,350,26,369,4186,109,52,1935,2384,161
South Dakota,184534470,62,82,13251.6242,-2.991505e+04,306.0,2373.6,822.1,3971.6,266.3,...,311,47,1,43,314,8,4,75,253,19
Tennessee,2845781724,1567,3450,196430.2335,-4.811868e+05,3231.0,85405.4,58112.6,114793.5,13952.6,...,4337,370,25,414,4029,135,91,2062,2332,212
Texas,4963502492,4183,4768,297435.8281,-9.408240e+05,5886.0,188575.5,139788.5,244016.7,17810.6,...,8651,720,30,619,8625,452,188,4513,3374,787
Utah,401691136,242,325,30837.9210,-8.525955e+04,623.0,9885.2,5812.9,14216.4,652.5,...,755,77,5,77,772,15,24,259,411,76
Vermont,140834002,49,61,14618.7035,-2.418540e+04,243.0,2547.4,1034.3,4069.8,425.6,...,306,28,1,9,323,6,3,147,172,9
Virginia,2269360597,1268,2827,161849.3659,-3.357212e+05,2253.0,67745.3,45480.2,91022.9,8786.1,...,3046,176,25,287,2851,90,57,1399,1600,163
Washington,1414731108,723,1092,124414.9380,-3.193832e+05,2279.0,30645.7,18924.2,43213.7,4346.6,...,2643,257,4,299,2670,66,67,866,1773,173
West Virginia,611138267,277,486,44428.1104,-9.363748e+04,872.0,13083.7,7760.2,18815.4,1882.9,...,1086,118,9,36,1148,36,22,380,670,66
Wisconsin,1624344828,767,1872,140643.4777,-2.874697e+05,1820.0,31034.2,16714.2,45516.9,5422.9,...,2148,139,7,271,2053,46,45,1003,1059,112
Wyoming,92156901,59,43,6721.4221,-1.683194e+04,150.0,1212.7,234.2,2241.5,73.6,...,145,18,1,4,156,4,1,19,105,26

In [5]:
gunstate.nunique()

incident_id                              51
n_killed                                 51
n_injured                                51
latitude                                 51
longitude                                51
n_guns_involved                          51
tavg                                     51
tmin                                     51
tmax                                     51
prcp                                     51
snow                                     47
wdir                                     51
wspd                                     51
wpgt                                      7
pres                                     51
tsun                                      6
set_weather                              50
day                                      51
month                                    51
year                                     51
day_of_the_week                          51
incident_amount                          50
participant_male                         51
participant_female                       49
participant_child                        45
participant_teen                         49
participant_adult                        50
participant_injured                      50
participant_injured_arrested             43
participant_unharmed                     50
participant_unharmed_arrested            50
participant_killed                       51
participant_victim                       51
participant_subject_suspect              50
participant_victim_male                  51
participant_victim_female                51
participant_victim_child                 40
participant_victim_teen                  49
participant_victim_adult                 51
participant_victim_injured               50
participant_victim_injured_arrested      24
participant_victim_unharmed              47
participant_victim_unharmed_arrested     27
participant_victim_killed                49
participant_suspect_male                 50
participant_suspect_female               47
participant_suspect_child                25
participant_suspect_teen                 50
participant_suspect_adult                51
participant_suspect_injured              42
participant_suspect_injured_arrested     39
participant_suspect_unharmed             50
participant_suspect_unharmed_arrested    50
participant_suspect_killed               47
dtype: int64

In [12]:
#eliminando columnas inútiles para el análisis
gunstate = gunstate[['n_guns_involved', 'n_injured', 'n_killed', 'incident_amount']]

In [14]:
gunstate.sort_values(by=['state'])
gunstate

                      n_guns_involved  n_injured  n_killed  incident_amount
state
Alabama                        2412.0       2580      1668             4427
Alaska                          750.0        267       234              932
Arizona                        1165.0        847       940             1687
Arkansas                       1365.0       1181       675             2165
California                     8835.0       6109      4872            12262
Colorado                       1404.0        681       627             1754
Connecticut                    1690.0       1047       305             2302
Delaware                        827.0        776       196             1365
District of Columbia            595.0       1004       390             1676
Florida                        6540.0       5532      3297            10213
Georgia                        3763.0       3360      2153             6538
Hawaii                          161.0         73        56              214
Idaho                           544.0        123       141              494
Illinois                       9553.0      12031      2909            14075
Indiana                        3481.0       2275      1346             4255
Iowa                           1145.0        619       232             1514
Kansas                          835.0        683       446             1356
Kentucky                       1990.0       1456       935             3038
Louisiana                      3683.0       3569      1854             6368
Maine                           603.0        127       102              601
Maryland                       2877.0       2811      1509             4786
Massachusetts                  3439.0       1345       414             3956
Michigan                       3143.0       2331      1319             4230
Minnesota                      1059.0        624       387             1309
Mississippi                    1482.0       1584      1015             2759
Missouri                       3243.0       2458      1828             4427
Montana                         380.0        103       136              409
Nebraska                        751.0        574       197             1083
Nevada                          728.0        704       672             1396
New Hampshire                   637.0        118        80              664
New Jersey                     2688.0       2216      1023             4347
New Mexico                      713.0        339       385              975
New York                       5612.0       4523      1556             8105
North Carolina                 3274.0       3643      1952             6303
North Dakota                    292.0         96        53              359
Ohio                           5757.0       4496      2152             7574
Oklahoma                       1501.0        885       775             1959
Oregon                         1525.0        593       377             1611
Pennsylvania                   4604.0       4264      2059             6971
Rhode Island                    513.0        298        50              654
South Carolina                 2800.0       2487      1403             5017
South Dakota                    306.0         82        62              302
Tennessee                      3231.0       3450      1567             5513
Texas                          5886.0       4768      4183             9669
Utah                            623.0        325       242              762
Vermont                         243.0         61        49              332
Virginia                       2253.0       2827      1268             4334
Washington                     2279.0       1092       723             2632
West Virginia                   872.0        486       277             1153
Wisconsin                      1820.0       1872       767             3248
Wyoming                         150.0         43        59              158

In [15]:
#request a la api del censo de los Estados Unidos
url = '	https://api.census.gov/data/2017/pep/population?get=GEONAME,POP,DENSITY&for=state:*&key=0ea84fc1d807f3a05a1b798c393c4899f95f2ea8'
popdf = requests.get(url)
print(popdf)

<Response [200]>

In [16]:
#revisando que el resultado de la query sea el esperado
texto=popdf.text
json.loads(texto)

[['GEONAME', 'POP', 'DENSITY', 'state'],
 ['District of Columbia', '693972', '11350.556038994', '11'],
 ['Florida', '20984400', '391.2517592529', '12'],
 ['Georgia', '10429379', '181.0726286368', '13'],
 ['Hawaii', '1427538', '222.2724611482', '15'],
 ['Idaho', '1716943', '20.7750524526', '16'],
 ['Illinois', '12802023', '230.6032631544', '17'],
 ['Indiana', '6666818', '186.0911143001', '18'],
 ['Iowa', '3145711', '56.3190899978', '19'],
 ['Kansas', '2913123', '35.6308902986', '20'],
 ['Kentucky', '4454189', '112.8066570405', '21'],
 ['Louisiana', '4684333', '108.4168500336', '22'],
 ['Maine', '1335907', '43.3116115053', '23'],
 ['Maryland', '6052177', '623.2458025617', '24'],
 ['Massachusetts', '6859819', '879.3603267562', '25'],
 ['Alabama', '4874747', '96.2499788716', '01'],
 ['Alaska', '739795', '1.2958713802', '02'],
 ['Arizona', '7016270', '61.7679734094', '04'],
 ['Arkansas', '3004279', '57.7365602082', '05'],
 ['California', '39536653', '253.7886617079', '06'],
 ['Colorado', '5607154', '54.1022981784', '08'],
 ['Connecticut', '3588184', '740.942005596', '09'],
 ['Delaware', '961939', '493.6182813018', '10'],
 ['Michigan', '9962311', '176.1390352347', '26'],
 ['Minnesota', '5576606', '70.0353989362', '27'],
 ['Mississippi', '2984100', '63.5955473683', '28'],
 ['Missouri', '6113532', '88.9289152989', '29'],
 ['Montana', '1050493', '7.2176302816', '30'],
 ['Nebraska', '1920076', '24.9950977374', '31'],
 ['Nevada', '2998039', '27.3094763514', '32'],
 ['New Hampshire', '1342795', '149.9873258423', '33'],
 ['New Jersey', '9005644', '1224.4015048951', '34'],
 ['New Mexico', '2088070', '17.2126798355', '35'],
 ['New York', '19849399', '421.2218721395', '36'],
 ['North Carolina', '10273419', '211.3095031757', '37'],
 ['North Dakota', '755393', '10.947647979', '38'],
 ['Ohio', '11658609', '285.3134356435', '39'],
 ['Oklahoma', '3930864', '57.3040390996', '40'],
 ['Oregon', '4142776', '43.1599086713', '41'],
 ['Pennsylvania', '12805537', '286.2078385063', '42'],
 ['Rhode Island', '1059639', '1024.8150920097', '44'],
 ['South Carolina', '5024369', '167.1281647808', '45'],
 ['South Dakota', '869666', '11.4717557282', '46'],
 ['Tennessee', '6715984', '162.871171736', '47'],
 ['Texas', '28304596', '108.3417398689', '48'],
 ['Utah', '3101833', '37.7373513713', '49'],
 ['Vermont', '623657', '67.659413865', '50'],
 ['Virginia', '8470020', '214.536337391', '51'],
 ['Washington', '7405743', '111.4437562253', '53'],
 ['West Virginia', '1815857', '75.5319649049', '54'],
 ['Wisconsin', '5795483', '107.005394869', '55'],
 ['Wyoming', '579315', '5.9666954483', '56'],
 ['Puerto Rico', '3337177', None, '72']]

In [17]:
#convirtiendo el json devuelto por la query a un dataframe de pandas
jsondata=json.loads(texto)
popdf2=pd.DataFrame.from_dict(jsondata)
#convirtiendo la primera fila en los nombres de las columnas del dataframe
popdf2.columns = popdf2.iloc[0]
popdf2 = popdf2.iloc[1: , :]
#renombrando columnas del dataset
popdf2.columns = ['state', 'total_population', 'density_sq_mi', 'state_n']
popdf2.head()

                  state total_population    density_sq_mi state_n
1  District of Columbia           693972  11350.556038994      11
2               Florida         20984400   391.2517592529      12
3               Georgia         10429379   181.0726286368      13
4                Hawaii          1427538   222.2724611482      15
5                 Idaho          1716943    20.7750524526      16

In [18]:
#convirtiendo columnas de object a numéricas para poder realizar cálculos
popdf2 = popdf2.astype({"total_population": int, "density_sq_mi": float})
popdf2.dtypes

state                object
total_population      int32
density_sq_mi       float64
state_n              object
dtype: object

In [19]:
#creando columna de densidad por km2 a partir de la de densidad por mi2
popdf2['density_sq_km'] = popdf2['density_sq_mi']*0.3861 
#droppeando columnas inútiles para el análisis
popdf2 = popdf2.drop(['density_sq_mi', 'state_n'], axis=1)
popdf2.drop(popdf2.index[51])
popdf2.head()

                  state  total_population  density_sq_km
1  District of Columbia            693972    4382.449687
2               Florida          20984400     151.062304
3               Georgia          10429379      69.912142
4                Hawaii           1427538      85.819397
5                 Idaho           1716943       8.021248

In [20]:
#mergeando los datos obtenidos del dataset inicial con los adquiridos de la api del censo
gunstatepop = pd.merge(gunstate, popdf2, on='state')
gunstatepop.sort_values(by=['total_population'])

,state,n_guns_involved,n_injured,n_killed,incident_amount,total_population,density_sq_km
50,Wyoming,150.0,43,59,158,579315,2.303741
45,Vermont,243.0,61,49,332,623657,26.123300
8,District of Columbia,595.0,1004,390,1676,693972,4382.449687
1,Alaska,750.0,267,234,932,739795,0.500336
34,North Dakota,292.0,96,53,359,755393,4.226887
41,South Dakota,306.0,82,62,302,869666,4.429245
7,Delaware,827.0,776,196,1365,961939,190.586018
26,Montana,380.0,103,136,409,1050493,2.786727
39,Rhode Island,513.0,298,50,654,1059639,395.681107
19,Maine,603.0,127,102,601,1335907,16.722613
29,New Hampshire,637.0,118,80,664,1342795,57.910107
11,Hawaii,161.0,73,56,214,1427538,85.819397
12,Idaho,544.0,123,141,494,1716943,8.021248
48,West Virginia,872.0,486,277,1153,1815857,29.162892
27,Nebraska,751.0,574,197,1083,1920076,9.650607
31,New Mexico,713.0,339,385,975,2088070,6.645816
16,Kansas,835.0,683,446,1356,2913123,13.757087
24,Mississippi,1482.0,1584,1015,2759,2984100,24.554241
28,Nevada,728.0,704,672,1396,2998039,10.544189
3,Arkansas,1365.0,1181,675,2165,3004279,22.292086
44,Utah,623.0,325,242,762,3101833,14.570391
15,Iowa,1145.0,619,232,1514,3145711,21.744801
6,Connecticut,1690.0,1047,305,2302,3588184,286.077708
36,Oklahoma,1501.0,885,775,1959,3930864,22.125089
37,Oregon,1525.0,593,377,1611,4142776,16.664041
17,Kentucky,1990.0,1456,935,3038,4454189,43.554650
18,Louisiana,3683.0,3569,1854,6368,4684333,41.859746
0,Alabama,2412.0,2580,1668,4427,4874747,37.162117
40,South Carolina,2800.0,2487,1403,5017,5024369,64.528184
23,Minnesota,1059.0,624,387,1309,5576606,27.040668
5,Colorado,1404.0,681,627,1754,5607154,20.888897
49,Wisconsin,1820.0,1872,767,3248,5795483,41.314783
20,Maryland,2877.0,2811,1509,4786,6052177,240.635204
25,Missouri,3243.0,2458,1828,4427,6113532,34.335454
14,Indiana,3481.0,2275,1346,4255,6666818,71.849779
42,Tennessee,3231.0,3450,1567,5513,6715984,62.884559
21,Massachusetts,3439.0,1345,414,3956,6859819,339.521022
2,Arizona,1165.0,847,940,1687,7016270,23.848615
47,Washington,2279.0,1092,723,2632,7405743,43.028434
46,Virginia,2253.0,2827,1268,4334,8470020,82.832480
30,New Jersey,2688.0,2216,1023,4347,9005644,472.741421
22,Michigan,3143.0,2331,1319,4230,9962311,68.007282
33,North Carolina,3274.0,3643,1952,6303,10273419,81.586599
10,Georgia,3763.0,3360,2153,6538,10429379,69.912142
35,Ohio,5757.0,4496,2152,7574,11658609,110.159518
13,Illinois,9553.0,12031,2909,14075,12802023,89.035920
38,Pennsylvania,4604.0,4264,2059,6971,12805537,110.504846
32,New York,5612.0,4523,1556,8105,19849399,162.633765
9,Florida,6540.0,5532,3297,10213,20984400,151.062304
43,Texas,5886.0,4768,4183,9669,28304596,41.830746
4,California,8835.0,6109,4872,12262,39536653,97.987802

In [22]:
#definiendo un diccionario para pasar los nombres de los estados a sus abreviaciones de dos letras
us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "U.S. Virgin Islands": "VI",
}

In [23]:
#cambiando nombres de estados a su abreviación de 2 letras
gunstatepop = gunstatepop.replace({"state": us_state_to_abbrev})
gunstatepop

,state,n_guns_involved,n_injured,n_killed,incident_amount,total_population,density_sq_km
0,AL,2412.0,2580,1668,4427,4874747,37.162117
1,AK,750.0,267,234,932,739795,0.500336
2,AZ,1165.0,847,940,1687,7016270,23.848615
3,AR,1365.0,1181,675,2165,3004279,22.292086
4,CA,8835.0,6109,4872,12262,39536653,97.987802
5,CO,1404.0,681,627,1754,5607154,20.888897
6,CT,1690.0,1047,305,2302,3588184,286.077708
7,DE,827.0,776,196,1365,961939,190.586018
8,DC,595.0,1004,390,1676,693972,4382.449687
9,FL,6540.0,5532,3297,10213,20984400,151.062304
10,GA,3763.0,3360,2153,6538,10429379,69.912142
11,HI,161.0,73,56,214,1427538,85.819397
12,ID,544.0,123,141,494,1716943,8.021248
13,IL,9553.0,12031,2909,14075,12802023,89.035920
14,IN,3481.0,2275,1346,4255,6666818,71.849779
15,IA,1145.0,619,232,1514,3145711,21.744801
16,KS,835.0,683,446,1356,2913123,13.757087
17,KY,1990.0,1456,935,3038,4454189,43.554650
18,LA,3683.0,3569,1854,6368,4684333,41.859746
19,ME,603.0,127,102,601,1335907,16.722613
20,MD,2877.0,2811,1509,4786,6052177,240.635204
21,MA,3439.0,1345,414,3956,6859819,339.521022
22,MI,3143.0,2331,1319,4230,9962311,68.007282
23,MN,1059.0,624,387,1309,5576606,27.040668
24,MS,1482.0,1584,1015,2759,2984100,24.554241
25,MO,3243.0,2458,1828,4427,6113532,34.335454
26,MT,380.0,103,136,409,1050493,2.786727
27,NE,751.0,574,197,1083,1920076,9.650607
28,NV,728.0,704,672,1396,2998039,10.544189
29,NH,637.0,118,80,664,1342795,57.910107
30,NJ,2688.0,2216,1023,4347,9005644,472.741421
31,NM,713.0,339,385,975,2088070,6.645816
32,NY,5612.0,4523,1556,8105,19849399,162.633765
33,NC,3274.0,3643,1952,6303,10273419,81.586599
34,ND,292.0,96,53,359,755393,4.226887
35,OH,5757.0,4496,2152,7574,11658609,110.159518
36,OK,1501.0,885,775,1959,3930864,22.125089
37,OR,1525.0,593,377,1611,4142776,16.664041
38,PA,4604.0,4264,2059,6971,12805537,110.504846
39,RI,513.0,298,50,654,1059639,395.681107
40,SC,2800.0,2487,1403,5017,5024369,64.528184
41,SD,306.0,82,62,302,869666,4.429245
42,TN,3231.0,3450,1567,5513,6715984,62.884559
43,TX,5886.0,4768,4183,9669,28304596,41.830746
44,UT,623.0,325,242,762,3101833,14.570391
45,VT,243.0,61,49,332,623657,26.123300
46,VA,2253.0,2827,1268,4334,8470020,82.832480
47,WA,2279.0,1092,723,2632,7405743,43.028434
48,WV,872.0,486,277,1153,1815857,29.162892
49,WI,1820.0,1872,767,3248,5795483,41.314783
50,WY,150.0,43,59,158,579315,2.303741